// <auto-generated />
using Denggaopan.GraphqlDemo.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Denggaopan.GraphqlDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20191121055058_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Denggaopan.GraphqlDemo.Entities.Item", b =>
                {
                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Barcode");

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Barcode = "123",
                            SellingPrice = 50m,
                            Title = "Headphone"
                        },
                        new
                        {
                            Barcode = "456",
                            SellingPrice = 40m,
                            Title = "Keyboard"
                        },
                        new
                        {
                            Barcode = "789",
                            SellingPrice = 100m,
                            Title = "Monitor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
